import type { PageConfig } from "./types";
import {
  genProdutos,
  genPessoasJuridicas,
  genMotoristas,
  genUsuarios,
  genVeiculos,
  genLocaisEstoque,
} from "../mock/generators";
import { EMPRESAS, TRANSPORTADORAS } from "../mock/pools";

const STATUS_OPTIONS = ["Ativo", "Inativo", "Pendente"];
const moduleLabel = "Cadastros";
const moduleHref = "/cadastros";

export const cadastros: Record<string, PageConfig> = {
  produtos: {
    moduleLabel,
    moduleHref,
    pageLabel: "Produtos",
    title: "Produtos",
    description: "Gerencie os produtos, materiais e itens utilizados nas operações da empresa.",
    primaryActionLabel: "Novo produto",
    filters: [
      { key: "codigo", label: "Código", type: "text", placeholder: "Ex: PRD-0001" },
      { key: "produto", label: "Descrição", type: "text", placeholder: "Buscar por descrição" },
      { key: "categoria", label: "Categoria", type: "select", options: ["Matéria-prima", "Embalagens", "Eletrônicos", "Ferramentas", "EPI", "Componentes", "Insumos Agrícolas", "Peças Automotivas", "Mobiliário", "Limpeza e Higiene"] },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "produto", label: "Produto" },
      { key: "categoria", label: "Categoria" },
      { key: "unidade", label: "Unidade", align: "center" },
      { key: "estoque", label: "Estoque", align: "right" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genProdutos(101),
  },
  clientes: {
    moduleLabel,
    moduleHref,
    pageLabel: "Clientes",
    title: "Clientes",
    description: "Cadastro geral de clientes utilizados nas operações comerciais e de faturamento.",
    primaryActionLabel: "Novo cliente",
    filters: [
      { key: "codigo", label: "Código", type: "text" },
      { key: "nome", label: "Razão social", type: "text", placeholder: "Buscar por nome" },
      { key: "cidade", label: "Cidade/UF", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nome", label: "Razão social" },
      { key: "cidade", label: "Cidade/UF" },
      { key: "contato", label: "Contato" },
      { key: "telefone", label: "Telefone" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genPessoasJuridicas(102, 18, EMPRESAS),
  },
  fornecedores: {
    moduleLabel,
    moduleHref,
    pageLabel: "Fornecedores",
    title: "Fornecedores",
    description: "Cadastro de fornecedores homologados para compras e suprimentos.",
    primaryActionLabel: "Novo fornecedor",
    filters: [
      { key: "codigo", label: "Código", type: "text" },
      { key: "nome", label: "Razão social", type: "text" },
      { key: "cidade", label: "Cidade/UF", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nome", label: "Razão social" },
      { key: "cidade", label: "Cidade/UF" },
      { key: "contato", label: "Contato" },
      { key: "telefone", label: "Telefone" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genPessoasJuridicas(103, 16, EMPRESAS),
  },
  transportadoras: {
    moduleLabel,
    moduleHref,
    pageLabel: "Transportadoras",
    title: "Transportadoras",
    description: "Cadastro de transportadoras parceiras para operações de frete e distribuição.",
    primaryActionLabel: "Nova transportadora",
    filters: [
      { key: "codigo", label: "Código", type: "text" },
      { key: "nome", label: "Razão social", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nome", label: "Razão social" },
      { key: "cidade", label: "Cidade/UF" },
      { key: "contato", label: "Contato" },
      { key: "telefone", label: "Telefone" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genPessoasJuridicas(104, 10, TRANSPORTADORAS),
  },
  motoristas: {
    moduleLabel,
    moduleHref,
    pageLabel: "Motoristas",
    title: "Motoristas",
    description: "Cadastro de motoristas vinculados às operações de transporte e expedição.",
    primaryActionLabel: "Novo motorista",
    filters: [
      { key: "codigo", label: "Código", type: "text" },
      { key: "nome", label: "Nome", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nome", label: "Nome" },
      { key: "cnh", label: "Categoria CNH", align: "center" },
      { key: "telefone", label: "Telefone" },
      { key: "veiculoVinculado", label: "Veículo vinculado" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genMotoristas(105),
  },
  veiculos: {
    moduleLabel,
    moduleHref,
    pageLabel: "Veículos",
    title: "Veículos",
    description: "Frota própria e agregada utilizada nas operações de transporte.",
    primaryActionLabel: "Novo veículo",
    filters: [
      { key: "placa", label: "Placa", type: "text" },
      { key: "modelo", label: "Modelo", type: "text" },
      { key: "tipo", label: "Tipo", type: "select", options: ["Truck", "Van", "Carreta", "Toco", "Utilitário", "Bitrem"] },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "placa", label: "Placa" },
      { key: "modelo", label: "Modelo" },
      { key: "tipo", label: "Tipo" },
      { key: "capacidadeKg", label: "Capacidade (kg)", align: "right" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genVeiculos(106),
  },
  usuarios: {
    moduleLabel,
    moduleHref,
    pageLabel: "Usuários",
    title: "Usuários",
    description: "Usuários com acesso ao sistema e seus perfis de utilização.",
    primaryActionLabel: "Novo usuário",
    filters: [
      { key: "nome", label: "Nome", type: "text" },
      { key: "perfil", label: "Perfil", type: "select", options: ["Administrador", "Operador de Logística", "Comprador", "Vendedor", "Financeiro", "Fiscal", "Gestor"] },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nome", label: "Nome" },
      { key: "email", label: "E-mail" },
      { key: "perfil", label: "Perfil" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genUsuarios(107),
  },
  "locais-estoque": {
    moduleLabel,
    moduleHref,
    pageLabel: "Locais de estoque",
    title: "Locais de estoque",
    description: "Estrutura de armazéns, docas e áreas utilizadas para armazenagem.",
    primaryActionLabel: "Novo local",
    filters: [
      { key: "local", label: "Local", type: "text" },
      { key: "tipo", label: "Tipo", type: "select", options: ["Armazém", "Doca", "Área de quarentena", "Pátio externo"] },
      { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "local", label: "Local" },
      { key: "tipo", label: "Tipo" },
      { key: "capacidadeOcupada", label: "Ocupação", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genLocaisEstoque(108),
  },
};
