import type { PageConfig } from "./types";
import {
  genOperacaoLogistica,
  genEstoque,
  genEnderecamento,
  genInventario,
  genMovimentacoes,
} from "../mock/generators";
import { EMPRESAS, TRANSPORTADORAS, LOCAIS_ESTOQUE } from "../mock/pools";

const moduleLabel = "Logística";
const moduleHref = "/logistica";
const STATUS_OPS = ["Pendente", "Em andamento", "Concluído", "Atrasado"];

export const logistica: Record<string, PageConfig> = {
  recebimento: {
    moduleLabel,
    moduleHref,
    pageLabel: "Recebimento",
    title: "Recebimento",
    description: "Conferência e entrada de mercadorias recebidas de fornecedores.",
    primaryActionLabel: "Novo recebimento",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Fornecedor", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Fornecedor" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Itens", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(401, 20, "REC", EMPRESAS),
  },
  estoque: {
    moduleLabel,
    moduleHref,
    pageLabel: "Estoque",
    title: "Estoque",
    description: "Posição consolidada de estoque por produto e local de armazenagem.",
    primaryActionLabel: "Novo ajuste de estoque",
    filters: [
      { key: "codigo", label: "Código", type: "text" },
      { key: "produto", label: "Produto", type: "text" },
      { key: "local", label: "Local", type: "select", options: [...LOCAIS_ESTOQUE] },
      { key: "status", label: "Status", type: "select", options: ["Disponível", "Reservado", "Baixo estoque", "Bloqueado"] },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "produto", label: "Produto" },
      { key: "local", label: "Local" },
      { key: "quantidade", label: "Quantidade", align: "right" },
      { key: "unidade", label: "Unidade", align: "center" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genEstoque(402),
  },
  enderecamento: {
    moduleLabel,
    moduleHref,
    pageLabel: "Endereçamento",
    title: "Endereçamento",
    description: "Mapeamento de produtos por endereço físico dentro dos locais de estoque.",
    primaryActionLabel: "Novo endereçamento",
    filters: [
      { key: "produto", label: "Produto", type: "text" },
      { key: "endereco", label: "Endereço", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["Ocupado", "Disponível", "Bloqueado"] },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "produto", label: "Produto" },
      { key: "endereco", label: "Endereço" },
      { key: "local", label: "Local" },
      { key: "quantidade", label: "Quantidade", align: "right" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genEnderecamento(403),
  },
  inventario: {
    moduleLabel,
    moduleHref,
    pageLabel: "Inventário",
    title: "Inventário",
    description: "Contagens de inventário e divergências entre saldo físico e sistêmico.",
    primaryActionLabel: "Novo inventário",
    filters: [
      { key: "produto", label: "Produto", type: "text" },
      { key: "local", label: "Local", type: "select", options: [...LOCAIS_ESTOQUE] },
      { key: "status", label: "Status", type: "select", options: ["Conferido", "Divergência", "Em contagem"] },
    ],
    columns: [
      { key: "codigo", label: "Código" },
      { key: "produto", label: "Produto" },
      { key: "local", label: "Local" },
      { key: "quantidadeSistema", label: "Qtd. sistema", align: "right" },
      { key: "quantidadeContada", label: "Qtd. contada", align: "right" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genInventario(404),
  },
  movimentacoes: {
    moduleLabel,
    moduleHref,
    pageLabel: "Movimentações",
    title: "Movimentações",
    description: "Histórico de entradas, saídas, transferências e ajustes de estoque.",
    primaryActionLabel: "Nova movimentação",
    filters: [
      { key: "produto", label: "Produto", type: "text" },
      { key: "tipo", label: "Tipo", type: "select", options: ["Entrada", "Saída", "Transferência", "Ajuste"] },
      { key: "status", label: "Status", type: "select", options: ["Concluído", "Pendente", "Cancelado"] },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "tipo", label: "Tipo" },
      { key: "produto", label: "Produto" },
      { key: "quantidade", label: "Quantidade", align: "right" },
      { key: "data", label: "Data" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genMovimentacoes(405),
  },
  picking: {
    moduleLabel,
    moduleHref,
    pageLabel: "Picking",
    title: "Picking",
    description: "Separação de itens dos pedidos de venda para expedição.",
    primaryActionLabel: "Nova tarefa de picking",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Pedido", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Pedido" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Itens", align: "right" },
      { key: "responsavel", label: "Separador" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(406, 18, "PIK", EMPRESAS),
  },
  packing: {
    moduleLabel,
    moduleHref,
    pageLabel: "Packing",
    title: "Packing",
    description: "Conferência e embalagem de pedidos separados, prontos para expedição.",
    primaryActionLabel: "Nova tarefa de packing",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Pedido", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Pedido" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Volumes", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(407, 16, "PAK", EMPRESAS),
  },
  expedicao: {
    moduleLabel,
    moduleHref,
    pageLabel: "Expedição",
    title: "Expedição",
    description: "Carregamento e saída de mercadorias para entrega aos clientes.",
    primaryActionLabel: "Nova expedição",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Cliente", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Cliente" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Volumes", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(408, 20, "EXP", EMPRESAS),
  },
  transferencias: {
    moduleLabel,
    moduleHref,
    pageLabel: "Transferências",
    title: "Transferências",
    description: "Transferências de mercadorias entre locais de estoque e filiais.",
    primaryActionLabel: "Nova transferência",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Destino", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Local destino" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Itens", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(409, 14, "TRF", LOCAIS_ESTOQUE),
  },
  devolucoes: {
    moduleLabel,
    moduleHref,
    pageLabel: "Devoluções",
    title: "Devoluções",
    description: "Devoluções de mercadorias recebidas de clientes ou enviadas a fornecedores.",
    primaryActionLabel: "Nova devolução",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Cliente/Fornecedor", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Cliente/Fornecedor" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Itens", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(410, 14, "DEV", EMPRESAS),
  },
  transportes: {
    moduleLabel,
    moduleHref,
    pageLabel: "Transportes",
    title: "Transportes",
    description: "Viagens e fretes contratados junto às transportadoras parceiras.",
    primaryActionLabel: "Novo transporte",
    filters: [
      { key: "numero", label: "Número", type: "text" },
      { key: "referencia", label: "Transportadora", type: "text" },
      { key: "status", label: "Status", type: "select", options: STATUS_OPS },
    ],
    columns: [
      { key: "numero", label: "Número" },
      { key: "referencia", label: "Transportadora" },
      { key: "data", label: "Data" },
      { key: "itens", label: "Volumes", align: "right" },
      { key: "responsavel", label: "Responsável" },
      { key: "status", label: "Status", render: "status" },
    ],
    rows: genOperacaoLogistica(411, 16, "TRP", TRANSPORTADORAS),
  },
};
